[package]
name = "mafia-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
eyre = "0.6.12"
mime_guess = "2.0.4"
minijinja = "1.0.21"
